coverage:
  # FIXME: Set these back to automatic once we up coverage more
  status:
    patch:
      default:
        threshold: 10%
        target: 30%
    project:
      default:
        threshold: 10%
        target: 30%
