# file for storing all countries and urls
from collections import defaultdict as dd

# indeed sites
country_indeed = dd(str)
country_monster = dd(str)

country_indeed['Argentina']             = 'https://ar.indeed.com'
country_indeed['Australia']             = 'https://au.indeed.com'
country_indeed['Austria']               = 'https://at.indeed.com'
country_indeed['Bahrain']               = 'https://bh.indeed.com'
country_indeed['Belgium']               = 'https://be.indeed.com'
country_indeed['Brazil']                = 'https://www.indeed.com.br'
country_indeed['Canada']                = 'https://ca.indeed.com'
country_indeed['Chile']                 = 'https://www.indeed.cl'
country_indeed['China']                 = 'https://cn.indeed.com'
country_indeed['Columbia']              = 'https://co.indeed.com'
country_indeed['Czech Republic']	    = 'https://cz.indeed.com'
country_indeed['Denmark']			    = 'https://dk.indeed.com'
country_indeed['Ecuador']			    = 'https://ec.indeed.com'
country_indeed['Egypt']			        = 'https://eg.indeed.com'
country_indeed['Finland']			    = 'https://fi.indeed.com'
country_indeed['France']			    = 'https://www.indeed.fr'
country_indeed['Germany']			    = 'https://de.indeed.com'
country_indeed['Greece']			    = 'https://gr.indeed.com'
country_indeed['Hong Kong']		        = 'https://www.indeed.hk'
country_indeed['Hungary']			    = 'https://hu.indeed.com'
country_indeed['India']			        = 'https://www.indeed.co.in'
country_indeed['Indonesia']		        = 'https://id.indeed.com'
country_indeed['Ireland']			    = 'https://ie.indeed.com'
country_indeed['Israel']			    = 'https://il.indeed.com'
country_indeed['Italy']			        = 'https://it.indeed.com'
country_indeed['Japan']			        = 'https://jp.indeed.com'
country_indeed['Kuwait']			    = 'https://kw.indeed.com'
country_indeed['Luxembourg']		    = 'https://lu.indeed.com'
country_indeed['Malaysia']		        = 'https://www.indeed.com.my'
country_indeed['Mexico']			    = 'https://www.indeed.com.mx'
country_indeed['Morocco']			    = 'https://ma.indeed.com'
country_indeed['Netherlands']		    = 'https://www.indeed.nl'
country_indeed['New Zealand']		    = 'https://nz.indeed.com'
country_indeed['Nigeria']			    = 'https://ng.indeed.com'
country_indeed['Norway']			    = 'https://no.indeed.com'
country_indeed['Oman']			        = 'https://om.indeed.com'
country_indeed['Pakistan']		        = 'https://www.indeed.com.pk'
country_indeed['Panama']			    = 'https://pa.indeed.com'
country_indeed['Peru']			        = 'https://www.indeed.com.pe'
country_indeed['Philippines']		    = 'https://www.indeed.com.ph'
country_indeed['Poland']			    = 'https://pl.indeed.com'
country_indeed['Portugal']		        = 'https://www.indeed.pt'
country_indeed['Qatar']			        = 'https://qa.indeed.com'
country_indeed['Romania']			    = 'https://ro.indeed.com'
country_indeed['Russia']			    = 'https://ru.indeed.com'
country_indeed['Saudi Arabia']	        = 'https://sa.indeed.com'
country_indeed['Singapore']		        = 'https://www.indeed.com.sg'
country_indeed['South Africa']	        = 'https://www.indeed.co.za'
country_indeed['South Korea']		    = 'https://kr.indeed.com'
country_indeed['Spain']			        = 'https://www.indeed.es'
country_indeed['Sweden']			    = 'https://se.indeed.com'
country_indeed['Switzerland']		    = 'https://www.indeed.ch'
country_indeed['Taiwan']			    = 'https://tw.indeed.com'
country_indeed['Thailand']		        = 'https://th.indeed.com'
country_indeed['Turkey']			    = 'https://tr.indeed.com'
country_indeed['Ukraine']			    = 'https://ua.indeed.com'
country_indeed['United Arab Emirates']  = 'https://www.indeed.ae'
country_indeed['United Kingdom']	    = 'https://www.indeed.co.uk'
country_indeed['United States']	        = 'https://www.indeed.com'
country_indeed['Uruguay']			    = 'https://uy.indeed.com'
country_indeed['Venezuela']		        = 'https://ve.indeed.com'
country_indeed['Vietnam']			    = 'https://vn.indeed.com'

# monster sites


country_monster['Austria'] = 'https://www.monster.at/jobs/suche'
country_monster['Belgium'] = 'https://www.monster.be/en/jobs/search'
country_monster['Canada'] = 'https://www.monster.ca/jobs/search'
country_monster['Czech Republic'] = 'https://www.monster.cz/prace/hledat'
country_monster['Finland'] = 'https://www.monster.fi/tyopaikat/haku'
country_monster['France'] = 'https://www.monster.fr/emploi/recherche'
country_monster['Germany'] = 'https://www.monster.de/jobs/suche'
country_monster['Ireland'] = 'https://www.monster.ie/jobs/search'
country_monster['Italy'] = 'https://www.monster.it/lavoro/cerca'
country_monster['Luxembourg'] = 'https://www.monster.lu/fr/emploi/recherche'
country_monster['Netherlands'] = 'https://www.monsterboard.nl/vacatures/zoeken'
country_monster['Spain'] = 'https://www.monster.es/trabajo/buscar'
country_monster['Sweden'] = 'https://www.monster.se/jobb/sok/'
country_monster['Switzerland'] = 'https://www.monster.ch/de/jobs/suche'
country_monster['United Kingdom'] = 'https://www.monster.co.uk/jobs/search'
country_monster['United States'] = 'https://www.monster.com/jobs/search'
country_monster['India'] = 'https://www.monster.com/jobs/search'


