# All paths are relative to this file.

# Paths.
output_path: 'search'

# Filters.
search_terms:
  region:
    province: 'ON'
    city:     'waterloo'
    domain:   'ca'
    radius:   25

  keywords:
    - 'Python'

black_list:
  - 'Infox Consulting'
  - 'Terminal'

# Logging level options are: critical, error, warning, info, debug, notset
log_level: 'error'
